version: '3.1'

services:
  # app:
  #   depends_on:
  #     - mongo
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.dev
  #   image: app
  #   container_name: newe-app
  #   restart: always
  #   ports:
  #     - 3000:3000
  #   env_file:
  #     - .env
  #   volumes:
  #     - .:/usr/src/app

  mongo:
    image: mongo
    container_name: arbol-blanco-mongo
    restart: unless-stopped
    ports:
      - ${MONGO_PORT:-27017}:27017
    env_file:
      - .env
    volumes:
      - ./mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}